name: domain
description: Domian package for project.
version: 0.0.1
publish_to: none
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # External packages
  flutter_bloc: ^7.0.0
  get_it: ^7.1.3
  equatable: ^2.0.2

  # Personal packages
  data:
    path: ../data

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: